### ISSUE TITLE
Deprecated option UsePrivilegeSeparation starting from 7.5

### ISSUE THREAD

**Issue by kmonticolo** [diodonfrost/ansible-role-ssh-hardening#1]
"UsePrivilegeSeparation" is deprecated from starting from 7.5

From https://www.openssh.com/txt/release-7.5:

>  * This release deprecates the sshd_config UsePrivilegeSeparation
>    option, thereby making privilege separation mandatory. Privilege
>    separation has been on by default for almost 15 years and
>    sandboxing has been on by default for almost the last five.

**Comment by diodonfrost** [comment]
Requested option added. Thanks!

**Comment by kmonticolo** [comment]
Thanks. Could you please make it a release? I'd like to get the changes during galaxy upgrade.

**Comment by diodonfrost** [comment]
done [release 1.0.1](https://github.com/diodonfrost/ansible-role-ssh-hardening/releases/tag/1.0.1)
